# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies, and  run linters
name: Rails - Install dependencies and run linters

on:
  push:
    branches: [ main, dev, github-actions ]
  pull_request:
    branches: [ main, dev, github-actions ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.84.0

      - name: Bundle Install
        run: |
          bundle install

      # Add or Replace any other security checks here
      - name: Run security checks
        run: |
          brakeman -q -w2
      # Add or Replace any other Linters here
      - name: Run linters
        run: |
          rubocop --parallel